# Generated by Django 3.0.3 on 2020-06-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0008_Rec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmed',
            name='Date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deaths',
            name='Date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recovered',
            name='Date',
            field=models.CharField(max_length=100),
        ),
    ]
