# Generated by Django 3.0.3 on 2020-06-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0009_auto_20200617_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmed',
            name='Date',
            field=models.DateField(max_length=100),
        ),
    ]
