# Generated by Django 3.0.3 on 2020-06-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0011_auto_20200624_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deaths',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='recovered',
            name='Date',
            field=models.DateField(),
        ),
    ]
